---
- name: Deploy from Nexus to Nginx
  hosts: localhost
  connection: local
  vars:
    # 1. Nexus 접속 정보 (변수로 받음)
    nexus_url: "http://localhost:8082/repository/view-release"
    # Nexus 저장소 경로: com/wiseman/frontend-app/{버전}/{파일명}
    artifact_path: "com/wiseman/frontend-app/{{ build_number }}/frontend-app-{{ build_number }}.tar.gz"
    # 다운로드 받을 임시 경로 지정
    temp_file: "/tmp/frontend-app-{{ build_number }}.tar.gz"
    
  tasks:
    - name: 1. 기존 파일들만 삭제 (Clean)
      shell: rm -rf /var/www/html/*
      ignore_errors: yes  # 폴더가 비어있어도 에러 안 나게 설정

    - name: 2. 웹 폴더 존재 확인
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: 3. Nexus에서 파일 다운로드
      get_url:
        url: "{{ nexus_url }}/{{ artifact_path }}"
        dest: "{{ temp_file }}"
        url_username: "{{ nexus_user }}"
        url_password: "{{ nexus_pass }}"
        force: yes

    - name: 4. 다운받은 파일 압축 해제
      unarchive:
        src: "{{ temp_file }}"
        dest: /var/www/html/
        remote_src: yes
        extra_opts:
          - --strip-components=1

    # (선택) 깔끔하게 임시 파일 삭제
    - name: 5. 임시 파일 삭제
      file:
        path: "{{ temp_file }}"
        state: absent

    - name: 6. 결과 확인
      debug:
        msg: "배포 완료! 버전 {{ build_number }}이(가) 설치되었습니다."